import { readFile } from 'node:fs/promises';

const escapeHtml = (value) =>
  String(value).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
  );
const scriptJson = (value) =>
  JSON.stringify(value)
    .replace(/</g, '\\u003c')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');

/** Embed package-owned assets so generated pages and exports have identical behavior. */
export async function renderZfbGallery(data, options = {}) {
  const [css, js] = await Promise.all([
    readFile(new URL('../client/app.css', import.meta.url), 'utf8'),
    readFile(new URL('../client/app.js', import.meta.url), 'utf8'),
  ]);
  const payload = { ...data, links: { ...(data.links || {}), ...options } };
  return `<style>${css.replace(/<\/style/gi, '<\\/style')}</style>\n<div id="diagram-app"></div>\n<noscript>This diagram workbench requires JavaScript. The SVG source files remain available in the session directory.</noscript>\n<script id="diagram-data" type="application/json">${scriptJson(payload)}</script>\n<script>${js.replace(/<\/script/gi, '<\\/script')}</script>`;
}

export async function renderGallery(data, options = {}) {
  const title = options.title || data.session.title;
  return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${escapeHtml(title)} · zudo-diagram-gen</title></head><body style="margin:0">${await renderZfbGallery(data, options)}</body></html>\n`;
}

/** Generates a route for the consumer renderer from validated data; Node I/O stays outside zfb's SSR graph. */
export async function createPageSource(data, options = {}, zfbMajor = 2) {
  if (![2, 3].includes(zfbMajor))
    throw new Error(`Unsupported zfb major: ${zfbMajor}. Expected 2 or 3.`);
  const html = await renderZfbGallery(data, options);
  const pragma =
    zfbMajor === 2 ? '/** @jsxRuntime automatic */\n/** @jsxImportSource preact */\n' : '';
  const charset = zfbMajor === 2 ? 'charSet' : 'charset';
  const bodyAttribute =
    zfbMajor === 2 ? 'dangerouslySetInnerHTML={{__html: body}}' : 'rawHtml={body}';
  return `// Generated by zudo-diagram-gen. Edit session files, not this route.\n${pragma}const body = ${JSON.stringify(html)};\nexport const frontmatter = {title: ${JSON.stringify(data.session.title)}};\nexport default function DiagramGalleryPage() {\n  return <html lang="en"><head><meta ${charset}="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="color-scheme" content="light dark"/><title>{frontmatter.title} · zudo-diagram-gen</title></head><body style={{margin:0}} ${bodyAttribute}/></html>;\n}\n`;
}

export { escapeHtml, scriptJson };
