import { readFile, writeFile, mkdir, readdir, lstat } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { loadSession } from './model.mjs';
import { createPageSource } from './render.mjs';

const marker = '// Generated by zudo-diagram-gen.';

export async function prepareProject(directory, zfbMajor = 2) {
  const root = resolve(directory);
  const data = await loadSession(root);
  const page = join(root, 'pages', 'index.tsx');
  for (const target of [join(root, 'pages'), page]) {
    try {
      if ((await lstat(target)).isSymbolicLink())
        throw new Error(
          'The generated gallery route must not be a symbolic link. Keep pages/index.tsx inside the session.',
        );
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
  let previous = '';
  try {
    previous = await readFile(page, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  if (previous && !previous.startsWith(marker))
    throw new Error(
      'pages/index.tsx belongs to this project. Use an initialized diagram session so the engine can own its route.',
    );
  const source = await createPageSource(data, {}, zfbMajor);
  if (source !== previous) {
    await mkdir(dirname(page), { recursive: true });
    await writeFile(page, source);
  }
  return data;
}

/** Watch the small content tree, including additions, with a portable polling scan. */
export async function contentSignature(directory) {
  const rows = [];
  async function visit(relative) {
    const full = join(directory, relative);
    let info;
    try {
      info = await lstat(full);
    } catch (error) {
      if (error.code === 'ENOENT') return;
      throw error;
    }
    if (info.isSymbolicLink()) {
      rows.push(`${relative}:symlink`);
      return;
    }
    if (info.isDirectory()) {
      const entries = await readdir(full, { withFileTypes: true });
      for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
        if (entry.isSymbolicLink()) {
          rows.push(`${relative}/${entry.name}:symlink`);
          continue;
        }
        await visit(join(relative, entry.name));
      }
    } else if (/\.(json|svg|md)$/i.test(relative)) {
      // Session validation rejects larger files. Track their metadata until they
      // become valid again rather than loading an unbounded file on each poll.
      const limit = /\.svg$/i.test(relative) ? 16 * 1024 * 1024 : 1024 * 1024;
      if (info.size > limit) rows.push(`${relative}:oversize:${info.size}:${info.mtimeMs}`);
      else {
        const contents = await readFile(full);
        rows.push(`${relative}:${createHash('sha256').update(contents).digest('hex')}`);
      }
    }
  }
  for (const path of ['session.json', 'brief.md', 'rounds']) await visit(path);
  return rows.join('\n');
}

export async function runZfb(command, directory = '.', forwarded = []) {
  const root = resolve(directory);
  const require = createRequire(join(root, 'package.json'));
  let manifest;
  try {
    manifest = require.resolve('@takazudo/zfb/package.json');
  } catch {
    throw new Error(
      'zfb is not installed in this session. Run pnpm install in its directory first.',
    );
  }
  const { version } = JSON.parse(await readFile(manifest, 'utf8'));
  const zfbMajor = Number(version.split('.')[0]);
  if (![2, 3].includes(zfbMajor))
    throw new Error(`Unsupported installed zfb version: ${version}. Expected zfb 2 or 3.`);
  const binary = join(dirname(manifest), 'bin', 'zfb.mjs');
  let signature = command === 'dev' ? await contentSignature(root) : '';
  if (command !== 'preview') await prepareProject(root, zfbMajor);
  // zfb owns output/base configuration and reports missing preview builds itself.
  const child = spawn(process.execPath, [binary, command, ...forwarded], {
    cwd: root,
    stdio: 'inherit',
  });
  const completion = new Promise((accept, reject) => {
    child.once('error', reject);
    child.once('exit', (code, signal) => accept(code ?? (signal === 'SIGINT' ? 130 : 1)));
  });
  let timer;
  let busy = false;
  if (command === 'dev')
    timer = setInterval(async () => {
      if (busy) return;
      busy = true;
      try {
        const next = await contentSignature(root);
        if (next !== signature) {
          signature = next;
          await prepareProject(root, zfbMajor);
          console.log('[diagram-gen] Updated gallery from session content.');
        }
      } catch (error) {
        console.error(
          `[diagram-gen] Content is not ready: ${error.message}. The last valid gallery remains displayed.`,
        );
      } finally {
        busy = false;
      }
    }, 650);
  const onInterrupt = () => child.kill('SIGINT');
  const onTerminate = () => child.kill('SIGTERM');
  process.on('SIGINT', onInterrupt);
  process.on('SIGTERM', onTerminate);
  try {
    return await completion;
  } finally {
    clearInterval(timer);
    process.off('SIGINT', onInterrupt);
    process.off('SIGTERM', onTerminate);
  }
}
