import { readFile, writeFile, mkdir, readdir, stat, lstat } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { loadSession } from './model.mjs';
import { createPageSource } from './render.mjs';

const marker = '// Generated by zudo-diagram-gen.';

export async function prepareProject(directory) {
  const root = resolve(directory);
  const data = await loadSession(root);
  const page = join(root, 'pages', 'index.tsx');
  for (const target of [join(root, 'pages'), page]) {
    try { if ((await lstat(target)).isSymbolicLink()) throw new Error('The generated gallery route must not be a symbolic link. Keep pages/index.tsx inside the session.'); }
    catch (error) { if (error.code !== 'ENOENT') throw error; }
  }
  let previous = '';
  try { previous = await readFile(page, 'utf8'); }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (previous && !previous.startsWith(marker)) throw new Error('pages/index.tsx belongs to this project. Use an initialized diagram session so the engine can own its route.');
  const source = await createPageSource(data);
  if (source !== previous) {
    await mkdir(dirname(page), { recursive: true });
    await writeFile(page, source);
  }
  return data;
}

/** Watch the small content tree, including additions, with a portable polling scan. */
export async function contentSignature(directory) {
  const rows = [];
  async function visit(relative) {
    const full = join(directory, relative);
    let info;
    try { info = await stat(full); } catch (error) { if (error.code === 'ENOENT') return; throw error; }
    if (info.isDirectory()) {
      const entries = await readdir(full, { withFileTypes: true });
      for (const entry of entries.sort((a,b) => a.name.localeCompare(b.name))) {
        if (entry.isSymbolicLink()) { rows.push(`${relative}/${entry.name}:symlink`); continue; }
        await visit(join(relative, entry.name));
      }
    } else if (/\.(json|svg|md)$/i.test(relative)) rows.push(`${relative}:${info.size}:${info.mtimeMs}`);
  }
  for (const path of ['session.json', 'brief.md', 'rounds']) await visit(path);
  return rows.join('\n');
}

export async function runZfb(command, directory = '.', forwarded = []) {
  const root = resolve(directory);
  const require = createRequire(join(root, 'package.json'));
  let binary;
  try { binary = join(dirname(require.resolve('@takazudo/zfb/package.json')), 'bin', 'zfb.mjs'); }
  catch { throw new Error('zfb is not installed in this session. Run pnpm install in its directory first.'); }
  let signature = command === 'dev' ? await contentSignature(root) : '';
  if (command !== 'preview') await prepareProject(root);
  // zfb owns output/base configuration and reports missing preview builds itself.
  const child = spawn(process.execPath, [binary, command, ...forwarded], { cwd: root, stdio: 'inherit' });
  const completion = new Promise((accept, reject) => {
    child.once('error', reject);
    child.once('exit', (code, signal) => accept(code ?? (signal === 'SIGINT' ? 130 : 1)));
  });
  let timer;
  let busy = false;
  if (command === 'dev') timer = setInterval(async () => {
    if (busy) return;
    busy = true;
    try {
      const next = await contentSignature(root);
      if (next !== signature) {
        signature = next;
        await prepareProject(root);
        console.log('[diagram-gen] Updated gallery from session content.');
      }
    } catch (error) { console.error(`[diagram-gen] Content is not ready: ${error.message}. The last valid gallery remains displayed.`); }
    finally { busy = false; }
  }, 650);
  const onInterrupt = () => child.kill('SIGINT');
  const onTerminate = () => child.kill('SIGTERM');
  process.on('SIGINT', onInterrupt);
  process.on('SIGTERM', onTerminate);
  try {
    return await completion;
  } finally {
    clearInterval(timer);
    process.off('SIGINT', onInterrupt);
    process.off('SIGTERM', onTerminate);
  }
}
