import { test } from 'vitest';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, mkdir, rm, rename } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { renderGallery, createPageSource } from '../packages/diagram-gen/src/render.mjs';
import { loadSession } from '../packages/diagram-gen/src/model.mjs';
import { prepareProject, contentSignature, runZfb } from '../packages/diagram-gen/src/runner.mjs';
import { createProject } from '../packages/create-zudo-diagram-gen/src/index.mjs';

test('portable HTML embeds all assets and preserves literal text without script breakout', async () => {
  const data = await loadSession('examples/tone-exploration');
  const hostile = '</script><script>window.injected=true</script><img src=x onerror="bad()">';
  data.session.title = hostile;
  data.brief = hostile;
  const html = await renderGallery(data);
  assert.ok(html.startsWith('<!doctype html>'));
  assert.ok(!html.includes('<script>window.injected=true</script>'));
  const payload = html.match(
    /<script id="diagram-data" type="application\/json">([\s\S]*?)<\/script>/,
  )[1];
  const read = JSON.parse(payload);
  assert.equal(read.session.title, hostile);
  assert.equal(read.brief, hostile);
  assert.equal(read.candidates[0].assets.light, data.candidates[0].assets.light);
  assert.ok(!/<(?:script[^>]*src|link[^>]*href)=/i.test(html));
  assert.ok(!html.includes(resolve('.')));
  const source = await createPageSource(data);
  assert.ok(source.startsWith('// Generated by zudo-diagram-gen.'));
  assert.ok(!source.includes('node:fs'));
});

test('prepare owns only its generated page and never overwrites an authored route', async () => {
  const temp = await mkdtemp(join(tmpdir(), 'diagram-prepare-'));
  try {
    const root = join(temp, 'session');
    await createProject({ destination: root });
    await prepareProject(root);
    const page = join(root, 'pages/index.tsx');
    assert.match(await readFile(page, 'utf8'), /diagram-app/);
    await writeFile(page, 'export default function CustomPage() {return null;}');
    await assert.rejects(prepareProject(root), /belongs to this project/);
    assert.equal(
      await readFile(page, 'utf8'),
      'export default function CustomPage() {return null;}',
    );
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
});

test('content discovery notices additions, renames and deletions while ignoring generated output', async () => {
  const temp = await mkdtemp(join(tmpdir(), 'diagram-watch-'));
  try {
    await createProject({ destination: temp });
    const before = await contentSignature(temp);
    await mkdir(join(temp, 'rounds/r01/new'), { recursive: true });
    await writeFile(join(temp, 'rounds/r01/new/candidate.json'), '{}');
    const added = await contentSignature(temp);
    assert.notEqual(added, before);
    await rename(join(temp, 'rounds/r01/new'), join(temp, 'rounds/r01/renamed'));
    const renamed = await contentSignature(temp);
    assert.notEqual(renamed, added);
    await mkdir(join(temp, 'pages'), { recursive: true });
    await writeFile(join(temp, 'pages/index.tsx'), 'ignored');
    assert.equal(await contentSignature(temp), renamed);
    await rm(join(temp, 'rounds/r01/renamed'), { recursive: true });
    assert.equal(await contentSignature(temp), before);
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
});

test('renderer selection preserves embedded data, links, and v2 callers', async () => {
  const data = await loadSession('examples/tone-exploration');
  data.session.title = '</title><script>window.injected=true</script>';
  data.brief = '</script><img src=x onerror="bad()">';
  const options = { homeUrl: '/home?x=1&y=2' };
  const legacy = await createPageSource(data, options);
  const current = await createPageSource(data, options, 3);
  assert.match(legacy, /@jsxImportSource preact/);
  assert.match(legacy, /dangerouslySetInnerHTML/);
  assert.doesNotMatch(current, /@jsxImportSource|dangerouslySetInnerHTML|charSet/);
  assert.match(current, /charset="utf-8"/);
  assert.match(current, /rawHtml=\{body\}/);
  const body = (source) =>
    JSON.parse(source.match(/const body = (.*);\nexport const frontmatter/)[1]);
  assert.equal(body(current), body(legacy));
  const payload = JSON.parse(body(current).match(/type="application\/json">(.*?)<\/script>/s)[1]);
  assert.equal(payload.session.title, data.session.title);
  assert.equal(payload.brief, data.brief);
  assert.equal(payload.links.homeUrl, options.homeUrl);
  assert.doesNotMatch(body(current), /<script>window.injected/);
  await assert.rejects(createPageSource(data, options, 4), /Unsupported zfb major/);
});

test('runner selects the renderer and binary from the destination-installed zfb', async () => {
  const temp = await mkdtemp(join(tmpdir(), 'diagram-installed-'));
  try {
    for (const major of [2, 3]) {
      const root = join(temp, `consumer-${major}`);
      await createProject({ destination: root });
      const installed = join(root, 'node_modules/@takazudo/zfb');
      await mkdir(join(installed, 'bin'), { recursive: true });
      await writeFile(
        join(installed, 'package.json'),
        JSON.stringify({
          name: '@takazudo/zfb',
          version: `${major}.21.1`,
          exports: { './package.json': './package.json' },
        }),
      );
      await writeFile(
        join(installed, 'bin/zfb.mjs'),
        `import { writeFileSync } from 'node:fs'; writeFileSync('invoked.json', JSON.stringify(process.argv.slice(2)));`,
      );
      assert.equal(await runZfb('build', root, ['--base', '/review/']), 0);
      assert.deepEqual(JSON.parse(await readFile(join(root, 'invoked.json'), 'utf8')), [
        'build',
        '--base',
        '/review/',
      ]);
      const source = await readFile(join(root, 'pages/index.tsx'), 'utf8');
      assert.equal(source.includes('@jsxImportSource preact'), major === 2);
      assert.equal(source.includes('rawHtml={body}'), major === 3);
    }
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
});

test('v3 JSON transport preserves literal reserved marker text without emitting boundaries', async () => {
  const data = await loadSession('examples/tone-exploration');
  const literal =
    'data-zfb-island="Demo" DATA-ZFB-ISLAND zr:1: ZR:1: <!--zr:1:test--> \\u0064ata-zfb-island </script>';
  data.brief = literal;
  data.session.title = literal;
  data.candidates[0].description = literal;
  data.candidates[0].assets.light = `<svg><desc>${literal}</desc></svg>`;
  const source = await createPageSource(data, {}, 3);
  const body = JSON.parse(source.match(/const body = (.*);\nexport const frontmatter/)[1]);
  const json = body.match(/type="application\/json">(.*?)<\/script>/s)[1];
  assert.doesNotMatch(json, /data-zfb-island|zr:1:|<\/script/i);
  assert.deepEqual(JSON.parse(json), { ...data, links: {} });
});
