import { test } from 'vitest';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, mkdir, rm, rename } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { renderGallery, createPageSource } from '../packages/diagram-gen/src/render.mjs';
import { loadSession } from '../packages/diagram-gen/src/model.mjs';
import { prepareProject, contentSignature } from '../packages/diagram-gen/src/runner.mjs';
import { createProject } from '../packages/create-zudo-diagram-gen/src/index.mjs';

test('portable HTML embeds all assets and preserves literal text without script breakout', async () => {
  const data = await loadSession('examples/tone-exploration');
  const hostile = '</script><script>window.injected=true</script><img src=x onerror="bad()">';
  data.session.title = hostile;
  data.brief = hostile;
  const html = await renderGallery(data);
  assert.ok(html.startsWith('<!doctype html>'));
  assert.ok(!html.includes('<script>window.injected=true</script>'));
  const payload = html.match(
    /<script id="diagram-data" type="application\/json">([\s\S]*?)<\/script>/,
  )[1];
  const read = JSON.parse(payload);
  assert.equal(read.session.title, hostile);
  assert.equal(read.brief, hostile);
  assert.equal(read.candidates[0].assets.light, data.candidates[0].assets.light);
  assert.ok(!/<(?:script[^>]*src|link[^>]*href)=/i.test(html));
  assert.ok(!html.includes(resolve('.')));
  const source = await createPageSource(data);
  assert.ok(source.startsWith('// Generated by zudo-diagram-gen.'));
  assert.ok(!source.includes('node:fs'));
});

test('prepare owns only its generated page and never overwrites an authored route', async () => {
  const temp = await mkdtemp(join(tmpdir(), 'diagram-prepare-'));
  try {
    const root = join(temp, 'session');
    await createProject({ destination: root });
    await prepareProject(root);
    const page = join(root, 'pages/index.tsx');
    assert.match(await readFile(page, 'utf8'), /diagram-app/);
    await writeFile(page, 'export default function CustomPage() {return null;}');
    await assert.rejects(prepareProject(root), /belongs to this project/);
    assert.equal(
      await readFile(page, 'utf8'),
      'export default function CustomPage() {return null;}',
    );
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
});

test('content discovery notices additions, renames and deletions while ignoring generated output', async () => {
  const temp = await mkdtemp(join(tmpdir(), 'diagram-watch-'));
  try {
    await createProject({ destination: temp });
    const before = await contentSignature(temp);
    await mkdir(join(temp, 'rounds/r01/new'), { recursive: true });
    await writeFile(join(temp, 'rounds/r01/new/candidate.json'), '{}');
    const added = await contentSignature(temp);
    assert.notEqual(added, before);
    await rename(join(temp, 'rounds/r01/new'), join(temp, 'rounds/r01/renamed'));
    const renamed = await contentSignature(temp);
    assert.notEqual(renamed, added);
    await mkdir(join(temp, 'pages'), { recursive: true });
    await writeFile(join(temp, 'pages/index.tsx'), 'ignored');
    assert.equal(await contentSignature(temp), renamed);
    await rm(join(temp, 'rounds/r01/renamed'), { recursive: true });
    assert.equal(await contentSignature(temp), before);
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
});
